const {
    ProjectSchema,
    AccountSchema,
    GlobalTransactionSchema,
    SocialMediaSchema,
    PermissionSchema,
    RolesSchema,
    thirdPartyWebAppSchema,
    userSchema,
  } = require("./aa_schema");
  const {
    TransactionSchema,
    walletSchema,
    samanBankTransactionSchema,
    nextPayTransactionSchema,
    mellatTransactionSchema,
  } = require("./wallet_schema");
  const {
    travelSchema,
    travelNumberSchema,
    deliveriesSchema,
    imageSchema,
    tagSchema,
    categorySchema,
    productSchema,
    orderSchema,
    sliderSchema,
    
  } = require("./travel_schema");
  const {
    taxiSchema,
    taxiOnlineSchema,
    taxiCounterSchema,
    TravelOptionSchema,
    DriversMessageBoxSchema,
    serviceTypeSchema,
    taxiOnlineTimeSchema,
    FeeSchema,
    advancedMixFactorSchema,
    boxsizeSchema,
    boxweightSchema,
    serviceCountSchema,
    optionChangeAcceptance
  } = require("./taxi_schema");
  const {
    ticketSchema,
    templateMessageSchema,
    supportPhoneSchema,
    socketScheme,
    PushSchema,
    nofitySchema,
    IosVersionScheme,
    googleMapApiKeysSchema,
    DriverVersionScheme,
    driverTelegramLinkSchema,
    DriverIosVersionScheme,
    driverBannerSchema,
    customerTemplateMessageSchema,
    customerMessageSchema,
    appVersionScheme,
    activeSystemSchema,
    bugReportingSchema,
    callerIdLogSchema,
  } = require("./support_schema");
  
  const { stationSocketScheme, stationSchema } = require("./station_schema");
  const {
    customerTurnOverSchema,
    taxiPonySchema,
    taxiTurnOverSchema,
    MarketerTurnOverSchema,
    OrganizationTurnOverSchema,
    CallHistorySchema,
    AgencyTurnOverSchema,
  } = require("./turnover_schema");
  const {
    areaCoefficientSchema,
    areaCostSchema,
    areaSchema,
    areaServiceFactorSchema,
    areaTimeFactorSchema,
    citySchema,
    costBaseFactorSchema,
    costDistanceFactorSchema,
    costTimeFactorSchema,
    mixFactorSchema,
    placeSchema,
    serviceFactorSchema,
    sourceLocationRequestSchema,
    mapIrRequestSchema,
    travelFactorSchema,
  } = require("./place_schema");
  const {
    commentSchema,
    rateTravelSchema,
    CancellationReasonsSchema,
  } = require("./comment_schema");
  const {
    discountSchema,
    NonGlobalDiscountAreaSchema,
  } = require("./promotion_schema");
  const {
    customerSchema,
    CustomersMessageBoxSchema,
  } = require("./customer_schema");
  
  const { MarketerSchema } = require("./marketer_schema");
  
  const { AgencySchema } = require("./agency_schema");
  module.exports = {
    Project: ProjectSchema,
    User: userSchema,
    Account: AccountSchema,
    Agency: AgencySchema,
    Permission: PermissionSchema,
    Roles: RolesSchema,
    DriversMessageBox: DriversMessageBoxSchema,
    SocialMedia: SocialMediaSchema,
    CustomersMessageBox: CustomersMessageBoxSchema,
    GlobalTransaction: GlobalTransactionSchema,
    Transaction: TransactionSchema,
    Wallet: walletSchema,
    Deliveries: deliveriesSchema,
    Image: imageSchema,
    Fee: FeeSchema,
    bugReporting: bugReportingSchema,
    SamanTransaction: samanBankTransactionSchema,
    NextPayTransaction: nextPayTransactionSchema,
    MellatTransaction: mellatTransactionSchema,
    Travel: travelSchema,
    TravelNumber: travelNumberSchema,
    Taxi: taxiSchema,
    AgencyTurnOver: AgencyTurnOverSchema,
    TaxiOnline: taxiOnlineSchema,
    TaxiCounter: taxiCounterSchema,
    TravelOption: TravelOptionSchema,
    ServiceType: serviceTypeSchema,
    Ticket: ticketSchema,
    TemplateMessage: templateMessageSchema,
    SupportPhone: supportPhoneSchema,
    PanelSocket: socketScheme,
    OnesignalPush: PushSchema,
    FCMPush: PushSchema,
    Notify: nofitySchema,
    IosVersion: IosVersionScheme,
    GoogleMapApiKey: googleMapApiKeysSchema,
    DriverVersion: DriverVersionScheme,
    DriverTelegramLink: driverTelegramLinkSchema,
    DriverIosVersion: DriverIosVersionScheme,
    DriverBanner: driverBannerSchema,
    CustomerTemplateMessage: customerTemplateMessageSchema,
    CustomerMessage: customerMessageSchema,
    AppVersion: appVersionScheme,
    ActiveSystem: activeSystemSchema,
    StationSocket: stationSocketScheme,
    Station: stationSchema,
    CustomerTurnOver: customerTurnOverSchema,
    TaxiPony: taxiPonySchema,
    TaxiTurnOver: taxiTurnOverSchema,
    MarketerTurnOver: MarketerTurnOverSchema,
    OrganizationTurnOver: OrganizationTurnOverSchema,
    AreaCoefficient: areaCoefficientSchema,
    AreaCost: areaCostSchema,
    NonGlobalDiscountArea: NonGlobalDiscountAreaSchema,
    Area: areaSchema,
    AreaServiceFactor: areaServiceFactorSchema,
    AreaTimeFactor: areaTimeFactorSchema,
    City: citySchema,
    BaseFactor: costBaseFactorSchema,
    DistanceFactor: costDistanceFactorSchema,
    TimeFactor: costTimeFactorSchema,
    MixFactor: mixFactorSchema,
    Place: placeSchema,
    InputFactor: serviceFactorSchema,
    SourceLocationRequest: sourceLocationRequestSchema,
    Factor: travelFactorSchema,
    Comment: commentSchema,
    RateTravel: rateTravelSchema,
    Discount: discountSchema,
    CancellationReason: CancellationReasonsSchema,
    Customer: customerSchema,
    marketer: MarketerSchema,
    advancedMixFactor: advancedMixFactorSchema,
    CallHistory: CallHistorySchema,
    taxiOnlineTime: taxiOnlineTimeSchema,
    mapIrRequest: mapIrRequestSchema,
    thirdPartyWebApp: thirdPartyWebAppSchema,
    CallerIdLog: callerIdLogSchema,
    boxsize: boxsizeSchema,
    boxweight: boxweightSchema,
    TagSchema:tagSchema,
    CategorySchema:categorySchema,
    ProductSchema:productSchema,
    OrderSchema :orderSchema ,
    SliderSchema :sliderSchema ,
    ServiceCountSchema :serviceCountSchema,
    OptionChangeAcceptance : optionChangeAcceptance 
  };
   